# Generated by Django 3.0.3 on 2020-02-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
