# Generated by Django 3.0.3 on 2020-02-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=32, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=64, verbose_name='password')),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
