# Generated by Django 3.0.3 on 2020-02-14 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Property<django.db.models.fields.AutoField>', max_length=20, verbose_name='Property Name')),
                ('description', models.CharField(default='', max_length=150, verbose_name='Property Description')),
                ('value', models.IntegerField(default=10, verbose_name='Property Value')),
                ('buildingType', models.CharField(choices=[('skyscraper1', 'Skyscraper1'), ('skyscraper2', 'Skyscraper2'), ('tripletowers1', 'Tripletowers1')], default='skyscraper1', max_length=100, verbose_name='building type')),
                ('tier', models.IntegerField(default=1, verbose_name='Property Tier')),
                ('rating', models.IntegerField(default=0, verbose_name='Property Rating')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('amount', models.IntegerField(verbose_name='Transaction Amount')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller', to=settings.AUTH_USER_MODEL)),
                ('target_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
            ],
            options={
                'verbose_name': 'Property Transaction',
                'verbose_name_plural': 'Property Transactions',
            },
        ),
    ]
