# Generated by Django 3.0.3 on 2020-02-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20200214_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(default='Property 2409fd59', max_length=20, verbose_name='Property Name'),
        ),
    ]
