# Generated by Django 3.0.3 on 2020-02-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20200214_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(default='Property 4786cf8c', max_length=20, verbose_name='Property Name'),
        ),
    ]
