# Generated by Django 3.0.3 on 2020-02-14 02:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20200214_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(default='Property cca4bb40', max_length=20, verbose_name='Property Name'),
        ),
        migrations.AlterField(
            model_name='propertytransaction',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Transaction Date'),
        ),
    ]
