# Generated by Django 3.0.3 on 2020-02-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20200214_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='buildingType',
        ),
        migrations.AddField(
            model_name='property',
            name='building_type',
            field=models.CharField(choices=[('skyscraper1', 'Skyscraper1'), ('skyscraper2', 'Skyscraper2'), ('tripletowers1', 'Tripletowers1')], default='skyscraper1', max_length=100, verbose_name='Building Type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(default='Property 00415c82', max_length=20, verbose_name='Property Name'),
        ),
    ]
