# Generated by Django 3.0.3 on 2020-02-14 03:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20200214_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(default='Property 795a85c2', max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='property',
            name='tier',
            field=models.IntegerField(default=1, verbose_name='Tier'),
        ),
        migrations.AlterField(
            model_name='property',
            name='value',
            field=models.IntegerField(default=10, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='propertytransaction',
            name='amount',
            field=models.IntegerField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='propertytransaction',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
